language: node_js
node_js:
  - 13

cache:
  directories:
    - node_modules

install:
  - npm install

git:
  submodules: false

before_script:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

script:
  - npm run build

after_script:
  - cd ./public

branches:
  only:
    - main
