language: node_js
node_js:
  - 13

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:

script:
  - npm run build

after_script:
  - cd ./public

branches:
  only:
    - main
